name: matheus
description: "A new Flutter project."
publish_to: "none"
version: 1.6.3

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  path_provider: ^2.1.4
  intl: ^0.19.0
  fluttertoast: ^8.0.9
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  font_awesome_flutter: ^10.7.0
  excel: ^4.0.6
  fl_chart: ^0.69.2
  process_run: ^0.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - "assets/images/icone.png"

flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/images/icone.png"
    
